config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :questions
  devise_for :users
  resources :stats
  root 'welcome#index'
  resources :accounts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
  # before_action :authenticate_user!
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy ]

  # GET /questions or /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1 or /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions or /questions.json
  def create
    response = Openai.new.question(question_params['text'])
    @question = Question.new(question_params)

    if @question.save!
      @question.update!(response:)
      redirect_to root_path
    else
      redirect_to root_path, notice: "Question was not saved."
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to question_url(@question), notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url, notice: "Question was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:text, :response)
    end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index
    @questions = Question.all.order(created_at: :desc)
    @question = Question.new
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/instances_helper.rb
module InstancesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Lolstat
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    .notice
      = notice
    .alert
      = alert
    .container
      = yield

app/views/questions/_form.html.haml
= form_with(model: question) do |form|
  - if question.errors.any?
    %div{:style => "color: red"}
      %h2
        = pluralize(question.errors.count, "error")
        prohibited this question from being saved:
      %ul
        - question.errors.each do |error|
          %li= error.full_message
  %div
    = form.label :text, style: "display: block"
    = form.text_field :text
  %div
    = form.submit

app/views/questions/_question.html.haml
%div{:id => "#{dom_id question}"}
  %p
    %strong Text:
    = question.text
  %p
    %strong Response:
    = question.response

app/views/questions/edit.html.haml
%h1 Editing question
= render "form", question: @question
%br/
%div
  = link_to "Show this question", @question
  |
  \#{link_to "Back to questions", questions_path}

app/views/questions/index.html.haml
%p{:style => "color: green"}= notice
%h1 Questions
#questions
  - @questions.each do |question|
    = render question
    %p
      = link_to "Show this question", question
= link_to "New question", new_question_path

app/views/questions/new.html.haml
%h1 New question
= render "form", question: @question
%br/
%div
  = link_to "Back to questions", questions_path

app/views/questions/show.html.haml
%p{:style => "color: green"}= notice
= render @question
%div
  = link_to "Edit this question", edit_question_path(@question)
  |
  \#{link_to "Back to questions", questions_path}
  
  \#{button_to "Destroy this question", @question, method: :delete}

app/views/stats/index.html.haml
= @request.body

app/views/welcome/index.html.haml
%h1 GTP-3.5 turbo model
= form_with(model: @question) do |form|
  %div
    = form.label 'tvoje otázka'
    = form.text_field :text
  %div
    = form.submit

%div{ style: 'margin-top: 50px' }
  %hr
  - @questions.each do |question|
    %p= question.text
    %p= question.response
    %hr